# Generated by Django 4.1.2 on 2023-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_number", models.IntegerField(null=True)),
                ("password", models.CharField(max_length=100, null=True)),
                ("username", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("slots", models.IntegerField(null=True)),
                ("last_order_date", models.DateField(blank=True, null=True)),
                (
                    "total_orders",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_order",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_num_packets", models.IntegerField(default=0)),
                ("available_products", models.JSONField(default=dict)),
            ],
        ),
    ]
