# Generated by Django 4.1.2 on 2023-07-30 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True, default='username')),
                ("password", models.CharField(max_length=100, null=True, default='password')),
                ("store_number", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("slots", models.IntegerField(null=True)),
                ("last_order_date", models.DateField(blank=True, null=True)),
                (
                    "total_orders",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_order",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_num_packets", models.IntegerField(default=0)),
                ("available_products", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
