# Generated by Django 4.1.2 on 2023-06-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "total_orders",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "current_order",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("last_order_date", models.DateField(blank=True, null=True)),
                ("total_number_of_orders", models.IntegerField(default=0)),
            ],
        ),
    ]
