# Generated by Django 4.1.2 on 2023-07-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="total_number_of_orders",
        ),
        migrations.AddField(
            model_name="store",
            name="available_products",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="store",
            name="slots",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="store_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="total_num_packets",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="store",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
