# Generated by Django 4.1.2 on 2023-07-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
