# Generated by Django 4.0.6 on 2025-08-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_variety'),
        ('stores', '0002_store_store_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='available_products',
        ),
        migrations.AddField(
            model_name='store',
            name='available_products',
            field=models.ManyToManyField(related_name='available_in_stores', through='stores.StoreProduct', to='products.product'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('store', 'product')},
        ),
    ]
