# Generated by Django 4.1.2 on 2025-08-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_storeproduct_remove_store_available_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="last_order_date",
        ),
        migrations.RemoveField(
            model_name="store",
            name="password",
        ),
        migrations.RemoveField(
            model_name="store",
            name="total_num_packets",
        ),
        migrations.RemoveField(
            model_name="store",
            name="total_orders",
        ),
        migrations.RemoveField(
            model_name="store",
            name="username",
        ),
    ]
