# Generated by Django 4.1.2 on 2023-07-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_rename_user_store_storeuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="storeuser",
            new_name="store_user",
        ),
        migrations.DeleteModel(
            name="StoreUser",
        ),
    ]
