# Generated by Django 4.1.2 on 2025-08-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0004_remove_store_last_order_date_remove_store_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="current_order",
        ),
        migrations.AddField(
            model_name="store",
            name="last_order_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
