# Generated by Django 4.1.2 on 2025-08-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_remove_store_current_order_store_last_order_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
