# Generated by Django 4.1.2 on 2025-08-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_store_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="contact_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
