# Generated by Django 4.1.2 on 2023-09-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_packets", models.PositiveIntegerField(default=0)),
                ("order_number", models.PositiveIntegerField(default=0)),
                ("products", models.JSONField(default=dict)),
            ],
        ),
    ]
