# Generated by Django 4.1.2 on 2025-08-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_total_cost_remove_order_total_packets"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pulled_for_processing",
            field=models.BooleanField(default=False),
        ),
    ]
