# Generated by Django 4.1.2 on 2025-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_pulled_for_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pulled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
