# Generated by Django 4.1.2 on 2025-08-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_pulled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderincludes",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
