# Generated by Django 4.1.2 on 2025-08-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_orderincludes_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(),
        ),
    ]
