# Generated by Django 4.1.2 on 2023-06-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variety", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100)),
                ("subgroup", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("new", models.BooleanField(default=False)),
            ],
        ),
    ]
