# Generated by Django 4.1.2 on 2023-06-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="group",
        ),
        migrations.RemoveField(
            model_name="product",
            name="new",
        ),
        migrations.RemoveField(
            model_name="product",
            name="subgroup",
        ),
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quickbooks_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_type",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="super_type",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="veg_type",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="variety",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
