# Generated by Django 4.1.2 on 2023-06-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_group_remove_product_new_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="item_number",
            field=models.IntegerField(null=True),
        ),
    ]
