# Generated by Django 4.1.2 on 2025-08-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="item_number",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
