# Generated by Django 4.1.2 on 2023-06-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="product_photos/"),
        ),
    ]
