# Generated by Django 4.1.2 on 2023-07-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
